name: Generate Docs PDF
on:
  schedule:
    - cron: "50 5 * * 0" # 5:50 UTC Weekly on Sundays
  workflow_dispatch:

jobs:
  pdf:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@a90bcbc6539c36a85cdfeb73f7e2f433735f215b # v2.15.0
        with:
          egress-policy: audit

      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6

      - name: Install Prince
        run: |
          curl https://www.princexml.com/download/prince-15.4.1-linux-generic-x86_64.tar.gz -O
          tar zxf prince-15.4.1-linux-generic-x86_64.tar.gz
          cd prince-15.4.1-linux-generic-x86_64
          yes "" | sudo ./install.sh

      - name: Build PDF
        run: npx docusaurus-prince-pdf --toc -u https://docs.projectbluefin.io -o pdf/bluefin.pdf

      - name: Upload results
        uses: actions/upload-artifact@bbbca2ddaa5d8feaa63e36b76fdaad77386f024f # v7
        with:
          name: bluefin
          # The output filename can be specified with --output option
          path: pdf/bluefin.pdf
          if-no-files-found: error
          overwrite: true

      - name: Upload Release Artifact
        if: github.event_name != 'pull_request'
        env:
          GITHUB_TOKEN: ${{ github.token }}
        run: |
          gh release upload --clobber 0.1 pdf/bluefin.pdf
